import { KindTemplate } from "./types";

export const DEFAULT_KIND_TEMPLATES: KindTemplate[] = [
	{
		id: "kind-1-default",
		type: "default",
		kind: 1,
		name: "Normal Note",
		description: "Simple text notes for quick thoughts, reminders, or short messages.",
		markup: "markdown",
		structured: false,
		folderName: "kind-1-notes",
		fields: [
			{ key: "title", tagType: "title", description: "Optional title", required: false },
			{ key: "topics", tagType: "topics", description: "Comma-separated topics (e.g., 'bitcoin, nostr')", required: false },
		],
	},
	{
		id: "kind-11-default",
		type: "default",
		kind: 11,
		name: "Discussion Thread OP",
		description: "Opening post for a discussion thread.",
		markup: "markdown",
		structured: false,
		folderName: "kind-11-threads",
		fields: [
			{ key: "title", tagType: "title", description: "Thread title (required)", required: true },
			{ key: "author", tagType: "text", description: "Author name", required: false },
			{ key: "summary", tagType: "text", description: "Brief summary", required: false },
			{ key: "topics", tagType: "topics", description: "Comma-separated topics (e.g., 'bitcoin, nostr')", required: false },
		],
	},
	{
		id: "kind-30023-default",
		type: "default",
		kind: 30023,
		name: "Long-form Article",
		description: "Structured articles with title, summary, and image support.",
		markup: "markdown",
		structured: false,
		folderName: "kind-30023-articles",
		fields: [
			{ key: "title", tagType: "title", description: "Article title (required)", required: true },
			{ key: "author", tagType: "text", description: "Author name", required: false },
			{ key: "summary", tagType: "text", description: "Article summary", required: false },
			{ key: "image", tagType: "text", description: "Image URL", required: false },
			{ key: "topics", tagType: "topics", description: "Comma-separated topics (e.g., 'bitcoin, nostr')", required: false },
		],
	},
	{
		id: "kind-30040-default",
		type: "default",
		kind: 30040,
		name: "Publication Index",
		description: "Publication index for books, magazines, or documentation with hierarchical structure.",
		markup: "asciidoc",
		structured: true,
		contentTemplateId: "kind-30041-default",
		useNKBIP08: true,
		folderName: "kind-30040-publications",
		fields: [
			{ key: "title", tagType: "title", description: "Publication title (required)", required: true },
			{ key: "author", tagType: "text", description: "Author name", required: false },
			{ key: "type", tagType: "text", description: "Publication type: book, illustrated, magazine, documentation, academic, blog", required: false },
			{ key: "version", tagType: "text", description: "Version or edition", required: false },
			{ key: "published_on", tagType: "text", description: "Publication date (e.g., 2003-05-13)", required: false },
			{ key: "published_by", tagType: "text", description: "Publisher or source", required: false },
			{ key: "summary", tagType: "text", description: "Brief description", required: false },
			{ key: "source", tagType: "text", description: "URL to original source", required: false },
			{ key: "image", tagType: "text", description: "Cover image URL", required: false },
			{ key: "auto_update", tagType: "text", description: "Auto-update: yes, ask, or no", required: false, nostrTag: "auto-update" },
			{ key: "topics", tagType: "topics", description: "Comma-separated topics (e.g., 'bitcoin, nostr')", required: false },
			{ key: "collection_id", tagType: "text", description: "NKBIP-08 collection identifier (C tag)", required: false },
			{ key: "version_tag", tagType: "text", description: "NKBIP-08 version identifier (e.g., kjv, drb)", required: false },
		],
	},
	{
		id: "kind-30041-default",
		type: "default",
		kind: 30041,
		name: "Publication Content",
		description: "Content for publications, stand-alone or nested under a publication index.",
		markup: "asciidoc",
		structured: false,
		folderName: "kind-30041-chapters",
		fields: [
			{ key: "title", tagType: "title", description: "Chapter/section title (required)", required: true },
			{ key: "image", tagType: "text", description: "Image URL", required: false },
			{ key: "summary", tagType: "text", description: "Article summary", required: false },
			{ key: "topics", tagType: "topics", description: "Comma-separated topics (e.g., 'bitcoin, nostr')", required: false },
		],
	},
	{
		id: "kind-30817-default",
		type: "default",
		kind: 30817,
		name: "Wiki Page (Markdown)",
		description: "Wiki-style pages using Markdown format.",
		markup: "markdown",
		structured: false,
		folderName: "kind-30817-wiki-md",
		fields: [
			{ key: "title", tagType: "title", description: "Wiki page title (required)", required: true },
			{ key: "author", tagType: "text", description: "Author name", required: false },
			{ key: "summary", tagType: "text", description: "Brief summary", required: false },
			{ key: "image", tagType: "text", description: "Image URL", required: false },
			{ key: "topics", tagType: "topics", description: "Comma-separated topics (e.g., 'bitcoin, nostr')", required: false },
		],
	},
	{
		id: "kind-30818-default",
		type: "default",
		kind: 30818,
		name: "Wiki Page (AsciiDoc)",
		description: "Wiki-style pages using AsciiDoc format.",
		markup: "asciidoc",
		structured: false,
		folderName: "kind-30818-wiki-adoc",
		fields: [
			{ key: "title", tagType: "title", description: "Wiki page title (required)", required: true },
			{ key: "author", tagType: "text", description: "Author name", required: false },
			{ key: "summary", tagType: "text", description: "Brief summary", required: false },
			{ key: "image", tagType: "text", description: "Image URL", required: false },
			{ key: "topics", tagType: "topics", description: "Comma-separated topics (e.g., 'bitcoin, nostr')", required: false },
		],
	},
];
